Append default port if not specified in --server flag
appcelerator-archive/amp pull request #1014
Opened 2017-04-15 18:20 UTC by neha-viswanathan

adds default port to --server option

```
amp -s localhost version

Client:
 Version:       v0.6.0-dev
 Build:         e75f63c5
 Server:        localhost:50101
 Go version:    go1.8
 OS/Arch:       darwin/amd64

Server:         
 Version:       v0.6.0-dev
 Build:         33dca96f
 Go version:    go1.8.1
 OS/Arch:       linux/amd64
```

2017-04-15 19:49 UTC, freignat91 approved these changes
LGTM, just add how to test in the description

2017-04-15 20:34 UTC, subfuzion requested changes

2017-04-15 20:34 UTC, subfuzion commented on cmd/amp/commands.go
> +	cmd.PersistentFlags().StringVarP(&opts.addr, "server", "s", "cloud.atomiq.io:50101", "Specify server (host:port)")
No, please don't add a default here

2017-04-15 20:35 UTC, subfuzion commented on cmd/amp/commands.go
> +	cmd.PersistentFlags().StringVarP(&opts.addr, "server", "s", "cloud.atomiq.io:50101", "Specify server (host:port)")
We only have a one single location for updating the default server to connect to. There should be no default for the flag here.

2017-04-16 17:59 UTC, subfuzion approved these changes

2017-04-16 17:59 UTC, merged