Vendor update
appcelerator-archive/amp pull request #1054
Opened 2017-04-24 20:11 UTC by bquenin

Fixes #1053

## To test
```
ampmake cleanall build
```

2017-04-24 23:21 UTC, freignat91 approved these changes
Test it ok adding packages for amp-ui. works well
I need it for amp-ui

2017-04-25 23:44 UTC, subfuzion commented on cli/out.go
> +		log.Printf("Error getting size: %s\n", err)
👍

2017-04-25 23:54 UTC, subfuzion requested changes
@bquenin Some really good catches in the PR. I only have one concern -- let's discuss in person. It basically has to do with all the sub-packages. I don't think they're necessary; in fact, I think we have been over-using them for a while. I think the basic premise for sub-packages is for grouping packages from multiple VCS locations under one logical package, as explained here: https://github.com/Masterminds/glide#q-why-does-glide-have-the-concept-of-sub-packages-when-go-doesnt. Also, as the final tip mentions here, we should generally try to reference the base package name if that works. Maintaining vendoring health has been a major hassle, but hoping to move in the opposite direction toward more simplification...

2017-04-26 00:03 UTC, bquenin commented
I didn't added the subpackages by hand, I just let `glide create` do it for me just for the record. But sure, we can remove them.

2017-04-26 00:07 UTC, subfuzion commented
@bquenin Interesting. It's been maybe two months now since I recreated `glide.yaml`, and we've just been updating it since. I guess I wasn't expecting such an explosion of sub-packages. It doesn't seem consistent with its own documentation. I don't know that we need to remove anything that was auto-generated, I'm just so leery about adding to it. Every time we've run into a vendoring problem, I usually ended up resolving it by pruning down, not adding... Gotta love vendoring!

2017-04-26 01:12 UTC, subfuzion approved these changes

2017-04-26 03:37 UTC, merged