Storage concurrent update
appcelerator-archive/amp pull request #1184
Opened 2017-05-12 07:28 UTC by bquenin

2017-05-17 22:13 UTC, subfuzion commented on data/storage/etcd/store.go
> +		input := proto.Clone(template)
It isn't immediately clear to me why this needs to be done each loop iteration. A comment would help...

2017-05-17 22:35 UTC, subfuzion commented on tests/integration/data/storage/etcd/store_test.go
> +				msg.Names = append(msg.Names, fmt.Sprintf("%d", i))
`i` is not going to be what you expect in your closure. Call your goroutine with a copy of `i` (eg, `go func(i int) {}(i)`).

2017-05-17 22:36 UTC, subfuzion requested changes
Looks good overall. See comment.

2017-05-17 22:45 UTC, bquenin commented on tests/integration/data/storage/etcd/store_test.go
> +				msg.Names = append(msg.Names, fmt.Sprintf("%d", i))
good catch :+1:

2017-05-17 22:50 UTC, subfuzion approved these changes

2017-05-17 22:55 UTC, subfuzion submitted a review, later dismissed

2017-05-17 22:55 UTC, subfuzion commented on tests/integration/data/storage/etcd/store_test.go
> +				msg.Names = append(msg.Names, fmt.Sprintf("%d", i))
Well, I guess the actual value didn't really matter anyway since you're just appending names and comparing the total. But anyway, thanks. 👍

2017-05-18 17:01 UTC, freignat91 submitted a review, later dismissed
LGTM, to be tested with UI (can't for now)

2017-05-18 17:39 UTC, freignat91 approved these changes

2017-05-18 17:39 UTC, merged