Portal custom dashboard
appcelerator-archive/amp pull request #1280
Opened 2017-05-29 17:30 UTC by freignat91

Add portal custom dashboard with team sharing capabilities.

![image](https://cloud.githubusercontent.com/assets/11798891/26557929/d267481a-4459-11e7-8b49-1f7df1f30f24.png)

2017-06-02 01:20 UTC, ndegory commented
@freignat91 
I'm trying to access the UI through local.appcelerator.io, when I try to register the Submit button has no effect. Probably a certificate / gateway issue, but I'm not sure what is the recommended procedure to go on, can we add it to the documentation?

2017-06-02 01:22 UTC, bquenin requested changes

2017-06-02 01:22 UTC, bquenin commented on api/rpc/dashboard/dashboard.go
> +		dashboard.Data = "" //remove data, data are loaded one by one using get
@freignat91 This line is causing the tests to fail. Tests need to be updated to reflect this modification.

2017-06-02 02:11 UTC, ndegory requested changes
I tried to access the UI through local.appcelerator.io, when I try to register the Submit button has no effect. Probably a certificate / gateway issue, but I'm not sure what is the recommended procedure to go on, can we add it to the documentation?
It would be great also to catch this issue and notify about it directly in the UI, most user won't look in the documentation on how to use a UI...
Ref #1220 and #1192 

{FR}-> for the certificate error message, it should be the case, its a bug. The error is trapped and a specific message is sent with saying that the certificat is not there and indicating to read doc.
However for local usage no certificate should be better to simplify the deployment.

For the record, adding the certificate in my system keychain didn't help, Chrome still refused the certificate. I had to accept the certificate for local.appcelerator.io, open another tab and type https://gw.local.appcelerator.io, accept the certificate, and go back to the UI to signup.

When deploying a stack with the CLI, there's a default name. The UI should do the same, when loading a file, it should use the basename.

{FR} that's a server issue, the default should be on server side, not on UI , nor on CLI, in order that UI and CLI benefit of them for free

In the dashboard UI, the rounded box checkbox doesn't have any effect (it's not really mandatory, but if we keep the checkbox, we should make sure it works). The default text for the legends should be changed (stack legend instead of legend stack)

{FR}: yes, rounded checkbox is not yet implemented. i'll remove them for now

Histo period should be changed to period (or range). The text for the 5 min range is 10 min. The text for 2 years is 1 years.

{FR}; yes, Ok

2017-06-02 02:17 UTC, freignat91 commented on api/rpc/dashboard/dashboard.go
> +		dashboard.Data = "" //remove data, data are loaded one by one using get
yes, to be fixed

2017-06-02 21:02 UTC, bquenin submitted a review, later dismissed

2017-06-02 22:47 UTC, bquenin commented
> When deploying a stack with the CLI, there's a default name. The UI should do the same, when loading a file, it should use the basename.
> 
> {FR} that's a server issue, the default should be on server side, not on UI , nor on CLI, in order that UI and CLI benefit of them for free

It's not a server feature, the server doesn't infer names (nad it cannot anyway). It's up to the client to pick his stack name.

2017-06-03 21:18 UTC, ndegory submitted a review, later dismissed

2017-06-03 23:12 UTC, ndegory approved these changes

2017-06-03 23:15 UTC, ndegory reviewed
@freignat91 please add .DS_Store in your global gitignore.

2017-06-03 23:16 UTC, merged