fix SignUp issue
appcelerator-archive/amp pull request #1297
Opened 2017-06-01 19:13 UTC by freignat91

Closes #1291 

Fix the SignUp error which didn't delete the user when internal error happened (as email not working) 

# test

- Do not install the SendGrid key 
- amp -s localhost cluster create -t local --registration=email --notifications=true
- amp -s localhost user signUp -> error SendGrid API key is empty
- amp -s localhost user signUp -> error SendGrid API key is empty

needed to signup to time, to verify the user as well been deleted at the first signUp error

2017-06-02 01:27 UTC, bquenin requested changes

2017-06-02 01:27 UTC, bquenin commented on data/accounts/store.go
> +const SignUpErrorContextValue = "SignUpError"
Dead code

2017-06-02 22:20 UTC, freignat91 commented on data/accounts/store.go
> +const SignUpErrorContextValue = "SignUpError"
oui, effectivement

2017-06-03 01:40 UTC, freignat91 commented on data/accounts/store.go
> +const SignUpErrorContextValue = "SignUpError"
done

2017-06-03 01:41 UTC, bquenin submitted a review, later dismissed

2017-06-04 23:36 UTC, bquenin approved these changes
LGTM

2017-06-04 23:36 UTC, merged