Disable some user and password cmds when `--registration=none`
appcelerator-archive/amp pull request #1362
Opened 2017-06-12 21:06 UTC by JosephGJ

resolves: #1232 

Disables the following cmds when `--registration=none`
```
amp user verify
amp user forgot-login
amp password reset
amp password set
```

2017-06-12 21:32 UTC, bquenin submitted a review, later dismissed
LGTM, however, instead of `codes.PermissionDenied`, `codes.Unimplemented` seems to better describe the status of the server in this particular situation, as the gRPC documentation states:
```
	// Unimplemented indicates operation is not implemented or not
	// supported/enabled in this service.
	Unimplemented Code = 12
```

2017-06-14 23:51 UTC, bquenin commented on cli/command/password/reset.go
> +	if reply.Info.Registration == "none" {
Can you replace `"none"` by its constant definition `configuration.RegistrationNone` located in `cmd/amplifier/server/configuration/configuration.go`

2017-06-14 23:51 UTC, bquenin commented on cli/command/password/set.go
> +	if reply.Info.Registration == "none" {
same

2017-06-14 23:51 UTC, bquenin commented on cli/command/password/set.go
> +	if reply.Info.Registration == "none" {
same

2017-06-14 23:52 UTC, bquenin requested changes
LGTM. Tested ok.

2017-06-14 23:52 UTC, bquenin commented on cli/command/password/reset.go
> +	if reply.Info.Registration == "none" {
Can you please replace `"none"` by its constant definition `RegistrationNone` located in `cmd/amplifier/server/configuration/configuration.go`?

2017-06-14 23:52 UTC, bquenin commented on cli/command/user/forgot-login.go
> +	if reply.Info.Registration == "none" {
same

2017-06-14 23:52 UTC, bquenin commented on cli/command/user/verify.go
> +	if reply.Info.Registration == "none" {
same

2017-06-14 23:55 UTC, bquenin commented on cli/command/password/set.go
> +	if reply.Info.Registration == "none" {
same

2017-06-15 17:19 UTC, JosephGJ commented on cli/command/password/reset.go
> +	if reply.Info.Registration == "none" {
done

2017-06-15 17:29 UTC, bquenin approved these changes

2017-06-15 17:33 UTC, merged