Org and Team commands remember the last used org/team
appcelerator-archive/amp pull request #1394
Opened 2017-06-16 18:43 UTC by JosephGJ

resolves: #1231 

Last used org/team is stored in a `server-preferences.yml`.

to test
```
$ make build-cli
$ amp -s localhost cluster create --tag=local
$ amp -s localhost org create --org=test --email=sample@email.com -> this will remember the org name now
$ amp -s localhost org member ls
[user jgrahamjones @ localhost:50101]
organization name: test <- automatically entered
MEMBER         ROLE
jgrahamjones   ORGANIZATION_OWNER
$ amp org remove test
[user jgrahamjones @ localhost:50101]
test <- check the server-preferences.yml to see that the org is blank
```
There are a number of commands that this can be tested with.

2017-06-26 18:01 UTC, neha-viswanathan requested changes
Please update for `amp team resource` command as well

2017-06-26 21:57 UTC, neha-viswanathan commented
Also, the preferences file should be removed when the user is deleted.

2017-06-27 04:58 UTC, subfuzion commented
@bquenin @neha-viswanathan What's the status of this PR?

2017-06-27 16:51 UTC, subfuzion commented
@bquenin @neha-viswanathan ^^

2017-06-27 16:51 UTC, subfuzion commented
@JosephGJ status?

2017-06-27 16:52 UTC, JosephGJ commented
The PR is finished.

2017-06-27 16:53 UTC, bquenin commented
@subfuzion I reviewed it yesterday. It looks good. Just need to address the file deletion on user rm and it's good to go.

2017-06-27 16:53 UTC, subfuzion commented
@JosephGJ Can you work with @bquenin and @neha-viswanathan to get this merged or is it going to be put on the icebox along with org support?

2017-06-27 16:55 UTC, JosephGJ commented
@subfuzion I can get this finished, I'll just add bertrands requested changes.

2017-06-27 22:03 UTC, neha-viswanathan approved these changes

2017-06-27 22:41 UTC, merged