Allow --template parameter for aws plugin
appcelerator-archive/amp pull request #1413
Opened 2017-06-22 18:44 UTC by subfuzion

Override the default Docker for AWS cloudformation template by specifying a url to a template with the `-t | --template` option.

2017-06-22 23:27 UTC, ndegory requested changes

2017-06-22 23:27 UTC, ndegory commented on cluster/plugin/aws/plugin.go
> +		TemplateURL:      aws.String(DefaultTemplateURL),
shouldn't it be opts.TemplateURL instead of DefaultTemplateURL?

2017-06-22 23:27 UTC, ndegory commented on cluster/plugin/aws/plugin.go
> +		TemplateURL:      aws.String(DefaultTemplateURL),
ditto

2017-06-23 00:16 UTC, subfuzion commented on cluster/plugin/aws/plugin.go
> +		TemplateURL:      aws.String(DefaultTemplateURL),
Yup to both ... I did a search/replace on templateURL to rename, but didn't switch these over to use the option now. Thanks for catching.

2017-06-23 00:45 UTC, ndegory submitted a review, later dismissed

2017-06-23 01:17 UTC, ndegory approved these changes

2017-06-23 01:17 UTC, merged