[WIP] Cluster test: networking and service scheduling
appcelerator-archive/amp pull request #1454
Opened 2017-06-27 23:40 UTC by ndegory

Test in the cluster/envoy image:
- docker version
  - checks that the Docker API is at least 1.29
- networking and service scheduling
  - creates an overlay network
  - creates a service on this network, with a placement constraint on nodes with label "amp.type.api==true"
  - creates a service on same network, with a placement constraint on nodes with label "amp.type.core==true"
  - the latter connects to the former
  - the connection rate is assessed

Expected output:
```

$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro appcelerator/amp-envoy  verifyDockerVersion
2017/06/27 23:33:28 Docker engine version 17.06.0-ce-rc5
2017/06/27 23:33:28 Test passed
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro appcelerator/amp-envoy  verifyServiceScheduling
2017/06/27 23:33:35 creating network amptest
2017/06/27 23:33:35 creating service check-server
2017/06/27 23:33:38 assertServiceHasRunningTasks(check-server) passed
2017/06/27 23:33:38 creating service check-client
2017/06/27 23:33:41 assertServiceHasRunningTasks(check-client) passed
2017/06/27 23:33:41 Counting request success rate...
2017/06/27 23:33:42 Test passed
2017/06/27 23:33:42 removing service check-client (ozqhoe20f2vgs90jol48ii4gr)
2017/06/27 23:33:42 removing service check-server (nvhmoe1k7fr2212drmmgdtk87)
2017/06/27 23:33:42 removing network amptest (reubveum6ytc6wj03dwcuu7t8)
```

2017-06-28 17:13 UTC, JosephGJ submitted a review, later dismissed
LGTM

2017-06-28 18:52 UTC, bquenin reviewed
Not related to your PR but it might be a good idea to reference the `cluster` folder in the `fmt` rule in the Makefile.

2017-06-29 18:48 UTC, subfuzion requested changes
@ndegory Looks good. I updated the makefile to keep it simple like other plugin. Please rename `envoyChecks.go` and then we're good to go. It won't be part of this PR, but we'll have to make some changes to what and how we print to stderr/stdout to be more CLI friendly.

2017-06-29 18:48 UTC, subfuzion commented on cluster/envoy/Dockerfile
> +RUN apk --no-cache add git gcc musl-dev
For what it's worth, you can also just use [build-base](https://pkgs.alpinelinux.org/package/v3.3/main/x86/build-base) as a good general base package (equivalent to build-essential) when you want to ensure you have a good base toolchain without thinking about each specific build tool.

2017-06-29 18:48 UTC, subfuzion commented on cluster/envoy/envoyChecks.go
> +package envoy
Just use lowercase for filenames, underscores as necessary, per Go conventions.

2017-06-29 20:27 UTC, subfuzion approved these changes

2017-06-29 20:27 UTC, merged