Logs message filter now takes regexes
appcelerator-archive/amp pull request #1582
Opened 2017-07-25 20:28 UTC by JosephGJ

fixes #1574 

Message flag now takes regexes.

2017-07-25 23:59 UTC, bquenin requested changes
That's a good start. You also need to tackle the logs streaming aspect and may want to add some tests.

2017-08-01 19:10 UTC, ndegory commented
@JosephGJ still planning for 0.14?

2017-08-01 20:57 UTC, JosephGJ commented
@ndegory I'll be able to get this in for 0.14, I'm just updating the smoke tests.

2017-08-01 21:33 UTC, bquenin approved these changes

2017-08-01 21:54 UTC, merged