Host labels for dashboards and alerts
appcelerator-archive/amp pull request #1645
Opened 2017-08-18 16:44 UTC by ndegory

Fix #1641 (Alerting and node identification)

The prometheus configuration now includes more information, in particular labels with the name of the host and the task id of the container. This allows to present useful information in dashboards and alerts, instead of the IP of the container.

## Verification

build the prometheus image ```make build-monit```
deploy amp ```amp cluster create```
Check the dashboard on dashboard.local.appcelerator.io, the instance name in the legends is now an IP instead of IP:port or container IP.

2017-08-23 21:23 UTC, bquenin requested changes
This code is doing a lot of things and I think a few unit tests wouldn't hurt.
Also, it doesn't seem to work:
![image](https://user-images.githubusercontent.com/11057786/29639141-8fd72b5c-880e-11e7-9a9f-0d2e1d05f0c1.png)

Here is my docker environment:
```
$ cat /etc/docker/daemon.json
{
	"dns": ["8.8.8.8","10.252.252.252"],
	"metrics-addr" : "0.0.0.0:9323",
	"experimental" : true,
	"storage-driver": "overlay2"
}
$ docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

2017-08-23 21:23 UTC, bquenin commented on monitoring/promctl/main.go
> +				StaticConfig{
Remove unnecessary type `StaticConfig` (from `make fmt`)

2017-08-23 21:23 UTC, bquenin commented on monitoring/promctl/main.go
> +			return nil, fmt.Errorf("unable to get metrics port label for service %s", name)
Shouldn't you `continue` to the next service instead of` return`ing immediately?

2017-08-23 21:23 UTC, bquenin commented on monitoring/promctl/main.go
> +			return nil, fmt.Errorf("Warning: service %s not found in network %s\n", name, monitoringNetwork)
Shouldn't you `continue` to the next service instead of` return`ing immediately?

2017-08-23 21:23 UTC, bquenin commented on monitoring/promctl/main.go
> +		metricsMode, ok := service.Spec.Annotations.Labels[metricsModeLabel]
I think it would more readable to check for unexpected values in the `switch` below, using a `default` statement.

2017-08-23 21:23 UTC, bquenin commented on monitoring/promctl/main.go
> +		case "tasks":
Defining constants for expected values (`tasks` and `exporter`) would be nice since you refer to these several times.

2017-08-23 21:23 UTC, bquenin commented on monitoring/promctl/main.go
> +func update(pid int, client *docker.Docker, configurationTemplate string, configuration string) error {
`pid` parameter is not used

2017-08-23 21:45 UTC, ndegory commented
@bquenin not sure why you don't have the dashboards. Can you also screenshot your http://alerts.local.appcelerator.io/targets and http://alerts.local.appcelerator.io/config?

2017-08-23 22:03 UTC, bquenin commented
@ndegory here it is:
![image](https://user-images.githubusercontent.com/11057786/29640545-4202a84c-8814-11e7-9026-933e00f31d31.png)
![image](https://user-images.githubusercontent.com/11057786/29640549-47182a96-8814-11e7-9546-ae8aee647bba.png)

2017-08-23 22:12 UTC, ndegory commented
@bquenin did it ever work for you on a Linux workstation? It seems the issue is that the hostname is not resolvable from the Prometheus container. This is not an issue on Docker for {Mac,Windows}, because it's the VM IP, and not an issue on real swarm cluster because the IPs are accessible.

2017-08-23 23:48 UTC, bquenin commented
@ndegory it was working in the past but I haven't checked recently. It seems that the issue is coming from the way the config is computed:
```
- job_name: docker-engine
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - u16-bbb127f9eae4:9323
```
I don't know where this comes from though, but on my machine name is only `u16`, not `u16-bbb127f9eae4`.

2017-08-24 02:30 UTC, bquenin approved these changes

2017-08-24 02:30 UTC, merged