add service save in etcd
appcelerator-archive/amp pull request #172
Opened 2016-09-15 17:15 UTC by freignat91

Relates to #162 

This PR adds the stack experimental API to amplifier.

## Verification
    $ ./swarm start
    $ make test-stack

2016-09-15 17:24 UTC, subfuzion commented on api/rpc/stack/stack_services.go
> +	err := s.Store.Create(ctx, stackRootKey+"/"+stackID+servicesRootKey+"/"+service.Name, val, nil, 0)
Nitpicking, but please use [path.Join](https://golang.org/pkg/path/#Join) instead.

2016-09-15 17:25 UTC, subfuzion requested changes
Looks good, just one nitpicky suggestion.

2016-09-15 17:26 UTC, subfuzion commented on api/rpc/stack/stack.go
> +	s.Store.Create(ctx, stackRootKey+"/"+stackID, stack, nil, 0)
Same comment as below about using `path.Join`...

2016-09-15 20:53 UTC, generalhenry commented on api/rpc/stack/stack_services.go
> +	data, _ := json.Marshal(service)
why json?

2016-09-15 20:54 UTC, generalhenry requested changes

2016-09-15 21:13 UTC, freignat91 commented on api/rpc/stack/stack_services.go
> +	err := s.Store.Create(ctx, stackRootKey+"/"+stackID+servicesRootKey+"/"+service.Name, val, nil, 0)
ok done

2016-09-15 21:13 UTC, freignat91 commented on api/rpc/stack/stack.go
> +	s.Store.Create(ctx, stackRootKey+"/"+stackID, stack, nil, 0)
done too

2016-09-15 21:33 UTC, freignat91 commented on api/rpc/stack/stack_services.go
> +	data, _ := json.Marshal(service)
right, i'm going to use the proto message directly

2016-09-15 21:43 UTC, freignat91 commented
Waiting for the last Tony's service proto service message to update the PR accordlingly

2016-09-15 22:30 UTC, subfuzion commented
#177 has been merged.

2016-09-15 22:33 UTC, subfuzion commented on api/rpc/stack/stack_services.go
> +	data, _ := json.Marshal(service)
Yep, only protobufs https://github.com/appcelerator/amp/blob/master/data/storage/interface.go#L24

2016-09-15 23:29 UTC, generalhenry approved these changes

2016-09-16 13:31 UTC, freignat91 commented on api/rpc/stack/stack_services.go
> +	data, _ := json.Marshal(service)
done

2016-09-16 13:42 UTC, freignat91 commented
Waiting for new parsing using service.ServiceSpect instead of stack.Service

2016-09-16 22:27 UTC, subfuzion commented
@freignat91 Closing this now -- go ahead and reopen it when you're ready.

2016-09-16 22:27 UTC, closed without merging