Implement cluster status and ls command in the API
appcelerator-archive/amp pull request #1766
Opened 2017-11-21 18:53 UTC by ndegory

Fix AMP-50

amp cluster status was implemented in the provider plugin (and not in all plugins), it is now part of the API. It also now contains more information about the context of the cluster: provider, region, output from the stack.

amp cluster ls and amp cluster node ls implementations were in the provider plugins and were not completed. amp cluster node ls is now part of the API, and provide extra information compared to what docker node ls provides: Version of the docker engine, available CPU and memory. It can also filter by node id, hostname and labels (engine or node).

This PR also include vendor updates necessary for this PR and the following one (object store API).

## Verification
```
ampmake build
# deploy a cluster on AWS, signup and login
amp -k -s CLUSTER_URL cluster node ls
# should show the full list of nodes, with their version, cpu and memory.
amp -k -s CLUSTER_URL cluster node ls --label amp.type.user
# only show the list of nodes with this label
amp -k -s CLUSTER_URL cluster node ls --id ANY_NODE_ID
# shows detailed information about this node, including its labels and plugins
```

2017-11-23 00:18 UTC, bquenin requested changes
It works but it feels that we have two commands combined into one.
I think it would be better to add another command such as `amp cluster node inspect` or `amp cluster node info` that would take a node ID as a parameter and displays details about the node. That would also be more consistent with the existing UX.

2017-11-23 00:18 UTC, bquenin commented on cli/command/cluster/nodeList.go
> +		fmt.Println("Found a single node, showing detailed information")
This should not be printed on the output. Put it in the command help.

2017-11-23 00:18 UTC, bquenin commented on cli/command/cluster/nodeList.go
> +		fmt.Println("Found multiple nodes, for detailed information about a particular node, you can filter with the --id or --name option")
This should not be printed on the output. Put it in the command help.

2017-11-23 01:44 UTC, ndegory commented
right, a node inspect command would make sense.

2017-11-27 22:29 UTC, bquenin approved these changes

2017-11-27 22:37 UTC, merged