ixing vendors
appcelerator-archive/amp pull request #1778
Opened 2017-12-02 04:21 UTC by bquenin

This PR fixes vendor (again).

The version for each dependency has been fixed so that we're less vulnerable to any transitive dependency update.
The code has been updated to comply with the new dependencies.

## How to test
Make sure you have the latest release version of dep (0.3.2):
```
$ dep version
dep:
 version     : v0.3.2
 build date  : 2017-10-19
 git hash    : 8ddfc8a
 go version  : go1.9
 go compiler : gc
 platform    : linux/amd64
```

Test with the following instructions:
```
$ rm -rf Gopkg.lock vendor
$ dep ensure
$ dep prune
```

Note that your vendor folder may differ from the one committed on this branch. It's probably because transitive dependencies might have been updated in the meantime. For more details on how `dep` works, please read https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-constrain-a-transitive-dependencys-version

Then make sure the code compiles and tests as expected:
```
$ ampmake clean build
$ amp cluster create
$ export PATH=tests/cli/testing:$PATH
$ TESTINCLUDE=tests/cli/testing testrunner tests/cli
$ docker run -it --rm --network core -v $PWD:/go/src/github.com/appcelerator/amp -w /go/src/github.com/appcelerator/amp appcelerator/amptools go test github.com/appcelerator/amp/tests/integration/... 
```

Check Travis build.

2017-12-06 00:26 UTC, ndegory requested changes
with latest version of dep. I would expect that dep ensure (without removing the lock file) would recreate the same vendor folder content.
```
$ rm -rf vendor
$ dep ensure
ensure Solve(): No versions of github.com/opencontainers/runc met constraints:
	v0.1.1: Could not introduce github.com/opencontainers/runc@v0.1.1 due to a case-only variation: it depends on "github.com/Sirupsen/logrus", but "github.com/sirupsen/logrus" was already established as the case variant for that project root by the following other dependers:
	(root)
	github.com/docker/distribution@edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c

	v0.1.0: Could not introduce github.com/opencontainers/runc@v0.1.0, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.9: Could not introduce github.com/opencontainers/runc@v0.0.9, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.8: Could not introduce github.com/opencontainers/runc@v0.0.8, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.7: Could not introduce github.com/opencontainers/runc@v0.0.7, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.6: Could not introduce github.com/opencontainers/runc@v0.0.6, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.5: Could not introduce github.com/opencontainers/runc@v0.0.5, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.4: Could not introduce github.com/opencontainers/runc@v0.0.4, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.3: Could not introduce github.com/opencontainers/runc@v0.0.3, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.2: Could not introduce github.com/opencontainers/runc@v0.0.2, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.1: Could not introduce github.com/opencontainers/runc@v0.0.1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc4: Could not introduce github.com/opencontainers/runc@v1.0.0-rc4, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc3: Could not introduce github.com/opencontainers/runc@v1.0.0-rc3, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc2: Could not introduce github.com/opencontainers/runc@v1.0.0-rc2, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc1: Could not introduce github.com/opencontainers/runc@v1.0.0-rc1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	master: Could not introduce github.com/opencontainers/runc@master, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	fs-named-cgroup: Could not introduce github.com/opencontainers/runc@fs-named-cgroup, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	relabel_fix_docker_1.9.1: Could not introduce github.com/opencontainers/runc@relabel_fix_docker_1.9.1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	resource-hf: Could not introduce github.com/opencontainers/runc@resource-hf, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.2.1: Could not introduce github.com/opencontainers/runc@v0.0.2.1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
```

2017-12-06 00:54 UTC, neha-viswanathan submitted a review, later dismissed
LGTM. Tested on Mac.

2017-12-06 00:56 UTC, neha-viswanathan commented
I don't find this discrepancy. I followed the test steps described in the PR as well as tried the steps by @ndegory.
```
$ rm -rf vendor
$ dep ensure
```

2017-12-06 01:26 UTC, ndegory commented
I've tested on Mac with different versions of dep, same result:
- dep from brew
- dep from go get (master)
- latest release (v0.3.2)

@neha-viswanathan can you please do the test again with:
rm -rf vendor
git checkout -- Gopkg.lock Gopkg.toml
dep ensure

2017-12-06 01:47 UTC, neha-viswanathan commented
@ndegory  tested with the steps you suggested. I don't see any errors.

2017-12-06 02:21 UTC, bquenin commented
@ndegory I couldn't reproduce this issue either. Can you please:
  * make sure you're using version 0.3.2
  * clean your dep cache and retry?
```
$ rm -rf $GOPATH/pkg/dep
```

2017-12-06 02:34 UTC, ndegory commented
```
~/Development/src/github.com/appcelerator/amp(vendor ✗) rm -rf $GOPATH/pkg/dep
~/Development/src/github.com/appcelerator/amp(vendor ✗) $GOPATH/bin/dep-darwin-amd64 version
dep:
 version     : v0.3.2
 build date  : 2017-10-19
 git hash    : 8ddfc8a
 go version  : go1.9
 go compiler : gc
 platform    : darwin/amd64
~/Development/src/github.com/appcelerator/amp(vendor ✗) $GOPATH/bin/dep-darwin-amd64 ensure
ensure Solve(): No versions of github.com/opencontainers/runc met constraints:
	v0.1.1: Could not introduce github.com/opencontainers/runc@v0.1.1 due to a case-only variation: it depends on "github.com/Sirupsen/logrus", but "github.com/sirupsen/logrus" was already established as the case variant for that project root by the following other dependers:
	(root)
	github.com/docker/distribution@edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c
	github.com/bshuster-repo/logrus-logstash-hook@0.4

	v0.1.0: Could not introduce github.com/opencontainers/runc@v0.1.0, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.9: Could not introduce github.com/opencontainers/runc@v0.0.9, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.8: Could not introduce github.com/opencontainers/runc@v0.0.8, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.7: Could not introduce github.com/opencontainers/runc@v0.0.7, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.6: Could not introduce github.com/opencontainers/runc@v0.0.6, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.5: Could not introduce github.com/opencontainers/runc@v0.0.5, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.4: Could not introduce github.com/opencontainers/runc@v0.0.4, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.3: Could not introduce github.com/opencontainers/runc@v0.0.3, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.2: Could not introduce github.com/opencontainers/runc@v0.0.2, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.1: Could not introduce github.com/opencontainers/runc@v0.0.1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc4: Could not introduce github.com/opencontainers/runc@v1.0.0-rc4, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc3: Could not introduce github.com/opencontainers/runc@v1.0.0-rc3, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc2: Could not introduce github.com/opencontainers/runc@v1.0.0-rc2, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v1.0.0-rc1: Could not introduce github.com/opencontainers/runc@v1.0.0-rc1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	master: Could not introduce github.com/opencontainers/runc@master, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	fs-named-cgroup: Could not introduce github.com/opencontainers/runc@fs-named-cgroup, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	relabel_fix_docker_1.9.1: Could not introduce github.com/opencontainers/runc@relabel_fix_docker_1.9.1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	resource-hf: Could not introduce github.com/opencontainers/runc@resource-hf, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
	v0.0.2.1: Could not introduce github.com/opencontainers/runc@v0.0.2.1, as it is not allowed by constraint 0.1.1 from project github.com/appcelerator/amp.
~/Development/src/github.com/appcelerator/amp(vendor ✗)
```

2017-12-06 03:03 UTC, bquenin commented
There are no occurrences of 'github.com/Sirupsen/logrus' (Uppercase 'S') in the repository, so it must come from somewhere in your `$GOPATH`.

Can you please run these commands in your `$GOPATH/src` :
```
$ cd $GOPATH/src
$ find . -type f -name '*.go' -not -path '*vendor*' -exec grep -l 'github.com/Sirupsen/logrus' {} \;
$ find . -type f -name '*.go' -not -path '*vendor*' -exec grep -l 'github.com/sirupsen/logrus' {} \;
./github.com/appcelerator/amp/cmd/gateway/main.go
./github.com/appcelerator/amp/cmd/agent/main.go
./github.com/appcelerator/amp/cmd/amplifier/server/configuration/configuration.go
./github.com/appcelerator/amp/cmd/amplifier/server/server.go
./github.com/appcelerator/amp/cmd/amplifier/main.go
./github.com/appcelerator/amp/pkg/docker/service.go
./github.com/appcelerator/amp/pkg/docker/stack.go
./github.com/appcelerator/amp/pkg/cloud/aws/aws.go
./github.com/appcelerator/amp/pkg/cloud/provider.go
./github.com/appcelerator/amp/pkg/nats-streaming/nats-streaming.go
./github.com/appcelerator/amp/api/rpc/cluster/cluster.go
./github.com/appcelerator/amp/api/rpc/config/config.go
./github.com/appcelerator/amp/api/rpc/resource/resource.go
./github.com/appcelerator/amp/api/rpc/account/account.go
./github.com/appcelerator/amp/api/rpc/secret/secret.go
./github.com/appcelerator/amp/api/rpc/logs/logs.go
./github.com/appcelerator/amp/api/rpc/service/service.go
./github.com/appcelerator/amp/api/rpc/stack/stack.go
./github.com/appcelerator/amp/api/rpc/object_store/object_store.go
./github.com/appcelerator/amp/agent/api.go
./github.com/appcelerator/amp/agent/config.go
./github.com/appcelerator/amp/agent/agent.go
./github.com/appcelerator/amp/agent/logs.go
./github.com/appcelerator/amp/agent/container.go
./github.com/appcelerator/amp/docker/cli/cli/flags/common.go
./github.com/appcelerator/amp/docker/cli/cli/compose/loader/loader.go
./github.com/appcelerator/amp/docker/cli/cli/command/out.go
./github.com/appcelerator/amp/docker/cli/cli/command/events_utils.go
./github.com/appcelerator/amp/docker/cli/cli/command/inspect/inspector.go
./github.com/appcelerator/amp/docker/docker/pkg/term/windows/windows.go
./github.com/appcelerator/amp/docker/docker/pkg/system/syscall_windows.go
./github.com/appcelerator/amp/docker/docker/registry/config.go
./github.com/appcelerator/amp/docker/docker/registry/service.go
./github.com/appcelerator/amp/docker/docker/registry/auth.go
./github.com/appcelerator/amp/docker/docker/registry/resumable/resumablerequestreader.go
./github.com/appcelerator/amp/docker/docker/registry/registry.go
./github.com/appcelerator/amp/docker/docker/registry/session.go
./github.com/appcelerator/amp/docker/docker/registry/endpoint_v1.go
./github.com/appcelerator/amp/data/accounts/authz.go
./github.com/appcelerator/amp/data/accounts/store.go
./github.com/appcelerator/amp/data/storage/etcd/store.go
./github.com/appcelerator/amp/data/storage/etcd/watcher.go
```

2017-12-06 04:05 UTC, ndegory commented
If my other projects' vendors impact what happens in amp, we're in trouble. I have indeed a few projects using a different case: 
```
ag -sl 'github.com/Sirupsen/logrus' -G .go$ .
gopkg.in/dancannon/gorethink.v1/gorethink.go
gopkg.in/dancannon/gorethink.v1/cluster.go
github.com/docker/infrakit.docker-metadata/cmd/main.go
github.com/docker/infrakit.docker-metadata/template.go
github.com/docker/infrakit/cmd/group/main.go
github.com/docker/infrakit/cmd/resource/main.go
github.com/docker/infrakit/examples/flavor/zookeeper/main.go
github.com/docker/infrakit/vendor/gopkg.in/inconshreveable/log15.v2/doc.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/archive/changes.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/archive/copy.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/archive/diff.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/archive/archive.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/archive/example_changes.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/system/syscall_windows.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/fileutils/fileutils_unix.go
github.com/docker/infrakit/vendor/github.com/docker/docker/pkg/fileutils/fileutils.go
github.com/docker/infrakit/vendor/github.com/docker/go-connections/sockets/unix_socket.go
github.com/docker/infrakit/vendor/github.com/docker/go-connections/tlsconfig/config.go
github.com/docker/infrakit/vendor/github.com/docker/go-connections/tlsconfig/certpool_other.go
github.com/docker/infrakit/vendor/github.com/docker/go-connections/tlsconfig/certpool_go17.go
github.com/docker/infrakit/vendor/github.com/Sirupsen/logrus/json_formatter.go
github.com/docker/infrakit/vendor/github.com/Sirupsen/logrus/doc.go
github.com/docker/infrakit/vendor/github.com/thebsdbox/go-tftp/server/readreq.go
github.com/docker/infrakit/vendor/github.com/thebsdbox/go-tftp/server/server.go
github.com/docker/infrakit/vendor/github.com/thebsdbox/go-tftp/server/writereq.go
github.com/docker/infrakit/pkg/broker/server/sse.go
github.com/docker/infrakit/pkg/broker/server/interceptor.go
github.com/docker/infrakit/pkg/util/docker/docker.go
github.com/docker/infrakit/pkg/launch/os/os_windows.go
github.com/docker/infrakit/pkg/launch/os/os_unix.go
github.com/docker/infrakit/pkg/plugin/instance/file/plugin.go
github.com/docker/infrakit/pkg/plugin/resource/plugin.go
github.com/docker/infrakit/pkg/provider/terraform/instance/cmd/main.go
github.com/docker/infrakit/pkg/provider/terraform/instance/plugin.go
github.com/docker/infrakit/pkg/provider/terraform/instance/apply.go
github.com/docker/infrakit/pkg/provider/ibmcloud/plugin/instance/volumeauthplugin.go
github.com/docker/infrakit/pkg/provider/docker/plugin/instance/instance.go
github.com/docker/infrakit/pkg/provider/vagrant/plugin/instance/instance.go
github.com/docker/infrakit/pkg/provider/google/plugin/group/plugin.go
github.com/docker/infrakit/pkg/provider/google/plugin/metadata/plugin.go
github.com/docker/infrakit/pkg/provider/digitalocean/plugin/instance/plugin.go
github.com/docker/infrakit/pkg/provider/oracle/client/core/subnet.go
github.com/docker/infrakit/pkg/provider/oracle/client/core/instance.go
github.com/docker/infrakit/pkg/provider/oracle/client/core/virtual_nic_attachment.go
github.com/docker/infrakit/pkg/provider/oracle/client/core/virtual_nic.go
github.com/docker/infrakit/pkg/provider/oracle/client/core/security_list.go
github.com/docker/infrakit/pkg/provider/oracle/client/core/virtual_network.go
github.com/docker/infrakit/pkg/provider/oracle/client/loadbalancer/certificate.go
github.com/docker/infrakit/pkg/provider/oracle/client/loadbalancer/backend.go
github.com/docker/infrakit/pkg/provider/oracle/client/loadbalancer/load_balancer.go
github.com/docker/infrakit/pkg/provider/oracle/client/loadbalancer/health_checker.go
github.com/docker/infrakit/pkg/provider/oracle/client/loadbalancer/backend_set.go
github.com/docker/infrakit/pkg/provider/oracle/client/loadbalancer/listener.go
github.com/docker/infrakit/pkg/provider/oracle/client/api/http_client.go
github.com/docker/infrakit/pkg/provider/oracle/client/api/client.go
github.com/docker/infrakit/pkg/provider/oracle/client/bmc/error.go
github.com/docker/infrakit/pkg/provider/oracle/client/bmc/config.go
github.com/docker/infrakit/pkg/provider/libvirt/plugin/instance/instance.go
github.com/docker/infrakit/pkg/provider/aws/experimental/bootstrap/cmd/infrakitctl/main.go
github.com/docker/infrakit/pkg/provider/aws/experimental/bootstrap/destroy.go
github.com/docker/infrakit/pkg/provider/aws/experimental/bootstrap/create.go
github.com/docker/infrakit/pkg/provider/aws/experimental/bootstrap/cli.go
github.com/docker/infrakit/pkg/provider/aws/experimental/bootstrap/formatter.go
github.com/docker/infrakit/pkg/provider/aws/plugin/loadbalancer/elb.go
github.com/docker/infrakit/pkg/provider/aws/plugin/instance/monitor.go
github.com/docker/infrakit/pkg/provider/aws/plugin/instance/autoscaling_autoscalinggroup.go
github.com/docker/infrakit/pkg/provider/aws/plugin/instance/ec2_spot_instance.go
github.com/docker/infrakit/pkg/provider/aws/plugin/instance/ec2_instance.go
github.com/docker/infrakit/pkg/provider/rackhd/plugin/instance/cmd/main.go
github.com/docker/infrakit/pkg/provider/rackhd/plugin/instance/instance.go
github.com/docker/infrakit/pkg/cli/logging.go
github.com/docker/infrakit/pkg/log/log.go
github.com/docker/infrakit/pkg/rpc/event/client.go
github.com/docker/infrakit/pkg/store/swarm/swarm.go
github.com/golang/dep/gps/solve_bimodal_test.go
github.com/LK4D4/vndr/test/testdata/dumbproject/pkg1/pkg.go
github.com/grafana/grafana/vendor/github.com/inconshreveable/log15/doc.go
github.com/rancher/trash/trash_test.go
github.com/rancher/trash/util/util.go
github.com/rancher/trash/trash.go
github.com/rancher/trash/conf/conf.go
github.com/rancher/trash/vendor/github.com/Sirupsen/logrus/json_formatter.go
github.com/rancher/trash/vendor/github.com/Sirupsen/logrus/doc.go
```

```
ag -sl 'github.com/sirupsen/logrus' -G .go$ .
github.com/appcelerator/amp/cmd/amplifier/server/configuration/configuration.go
github.com/appcelerator/amp/cmd/amplifier/server/server.go
github.com/appcelerator/amp/cmd/amplifier/main.go
github.com/appcelerator/amp/cmd/agent/main.go
github.com/appcelerator/amp/cmd/gateway/main.go
github.com/appcelerator/amp/docker/docker/registry/config.go
github.com/appcelerator/amp/docker/docker/registry/service.go
github.com/appcelerator/amp/docker/docker/registry/auth.go
github.com/appcelerator/amp/docker/docker/registry/session.go
github.com/appcelerator/amp/docker/docker/registry/registry.go
github.com/appcelerator/amp/docker/docker/registry/resumable/resumablerequestreader.go
github.com/appcelerator/amp/docker/docker/registry/endpoint_v1.go
github.com/appcelerator/amp/docker/docker/pkg/term/windows/windows.go
github.com/appcelerator/amp/docker/docker/pkg/system/syscall_windows.go
github.com/appcelerator/amp/docker/cli/cli/flags/common.go
github.com/appcelerator/amp/docker/cli/cli/compose/loader/loader.go
github.com/appcelerator/amp/docker/cli/cli/command/events_utils.go
github.com/appcelerator/amp/docker/cli/cli/command/inspect/inspector.go
github.com/appcelerator/amp/docker/cli/cli/command/out.go
github.com/appcelerator/amp/agent/config.go
github.com/appcelerator/amp/agent/api.go
github.com/appcelerator/amp/agent/logs.go
github.com/appcelerator/amp/agent/agent.go
github.com/appcelerator/amp/agent/container.go
github.com/appcelerator/amp/api/rpc/cluster/cluster.go
github.com/appcelerator/amp/api/rpc/object_store/object_store.go
github.com/appcelerator/amp/api/rpc/config/config.go
github.com/appcelerator/amp/api/rpc/logs/logs.go
github.com/appcelerator/amp/api/rpc/secret/secret.go
github.com/appcelerator/amp/api/rpc/stack/stack.go
github.com/appcelerator/amp/api/rpc/account/account.go
github.com/appcelerator/amp/api/rpc/service/service.go
github.com/appcelerator/amp/api/rpc/resource/resource.go
github.com/appcelerator/amp [...]

2017-12-06 04:06 UTC, ndegory commented
makes me think we should add dep in our gotools image and run it with ampmake to avoid any environmental impact.

2017-12-06 19:01 UTC, bquenin commented
@ndegory yeah, adding dep to our build tools could fix your issue. Please open a ticket.

2017-12-11 19:32 UTC, ndegory commented
now that the branch is rebased on master with the ampmake target for vendor installation, I still have the issue:
(vendor ✗) rm -rf $GOPATH/pkg/
(vendor ✗) mkdir $GOPATH/pkg/
(vendor ✗) ampmake install-vendor
Using existing GOPATH: REDACTED
ensure Solve(): No versions of github.com/docker/distribution met constraints:
	edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c: Could not introduce github.com/docker/distribution@edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c due to a case-only variation: it depends on "github.com/sirupsen/logrus", but "github.com/Sirupsen/logrus" was already established as the case variant for that project root by depender (root)
	v2.6.2: Could not introduce github.com/docker/distribution@v2.6.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.6.1: Could not introduce github.com/docker/distribution@v2.6.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.6.0: Could not introduce github.com/docker/distribution@v2.6.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.5.2: Could not introduce github.com/docker/distribution@v2.5.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.5.1: Could not introduce github.com/docker/distribution@v2.5.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.5.0: Could not introduce github.com/docker/distribution@v2.5.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.4.1: Could not introduce github.com/docker/distribution@v2.4.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.4.0: Could not introduce github.com/docker/distribution@v2.4.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.3.1: Could not introduce github.com/docker/distribution@v2.3.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.3.0: Could not introduce github.com/docker/distribution@v2.3.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.2.1: Could not introduce github.com/docker/distribution@v2.2.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.2.0: Could not introduce github.com/docker/distribution@v2.2.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.1.1: Could not introduce github.com/docker/distribution@v2.1.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.1.0: Could not introduce github.com/docker/distribution@v2.1.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.1: Could not introduce github.com/docker/distribution@v2.0.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.0: Could not introduce github.com/docker/distribution@v2.0.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.6.1-rc.2: Could not introduce github.com/docker/distribution@v2.6.1-rc.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.6.1-rc.1: Could not introduce github.com/docker/distribution@v2.6.1-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.6.0-rc.2: Could not introduce github.com/docker/distribution@v2.6.0-rc.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.6.0-rc.1: Could not introduce github.com/docker/distribution@v2.6.0-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.5.1-rc.1: Could not introduce github.com/docker/distribution@v2.5.1-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.5.0-rc.2: Could not introduce github.com/docker/distribution@v2.5.0-rc.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.5.0-rc.1: Could not introduce github.com/docker/distribution@v2.5.0-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.4.1-rc.2: Could not introduce github.com/docker/distribution@v2.4.1-rc.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.4.1-rc.1: Could not introduce github.com/docker/distribution@v2.4.1-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.4.1-rc.0: Could not introduce github.com/docker/distribution@v2.4.1-rc.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.4.0-rc.1: Could not introduce github.com/docker/distribution@v2.4.0-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.4.0-rc.0: Could not introduce github.com/docker/distribution@v2.4.0-rc.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.3.1-rc.0: Could not introduce github.com/docker/distribution@v2.3.1-rc.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.3.0-rc.2: Could not introduce github.com/docker/distribution@v2.3.0-rc.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.3.0-rc.1: Could not introduce github.com/docker/distribution@v2.3.0-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.3.0-rc.0: Could not introduce github.com/docker/distribution@v2.3.0-rc.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.3.0-alpha: Could not introduce github.com/docker/distribution@v2.3.0-alpha, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.1.0-rc.0: Could not introduce github.com/docker/distribution@v2.1.0-rc.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.0-rc.4: Could not introduce github.com/docker/distribution@v2.0.0-rc.4, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.0-rc.3: Could not introduce github.com/docker/distribution@v2.0.0-rc.3, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.0-rc.2: Could not introduce github.com/docker/distribution@v2.0.0-rc.2, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.0-rc.1: Could not introduce github.com/docker/distribution@v2.0.0-rc.1, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.0-rc.0: Could not introduce github.com/docker/distribution@v2.0.0-rc.0, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker.io/go-docker.
	v2.0.0-alpha.3: Could not introduce github.com/docker/distribution@v2.0.0-alpha.3, as it is not allowed by constraint edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c from project docker [...]

2017-12-12 16:57 UTC, ndegory commented
Working great now with the --vendor-only.

2017-12-12 16:57 UTC, ndegory approved these changes

2017-12-12 16:58 UTC, merged