Adds support for amp service create -p, and tests
appcelerator-archive/amp pull request #197
Opened 2016-09-19 22:24 UTC by subfuzion

The CLI now supports `amp service create -p` where `-p` is the input string for a `PublishSpec`.

## Verification

    $ go test -run TestRegex github.com/appcelerator/amp/api/rpc/service -v
    $ amp service create -p 3000:3000 appcelerator/pinger
    $ curl localhost:3000/ping
    pong

2016-09-19 23:08 UTC, generalhenry commented on api/rpc/service/helpers_test.go
> +		{input: "host-:4000:3000/udp", expect: PublishSpec{InternalPort: 3000, PublishPort: 4000, Protocol: "udp"}},
These lines are throwing a build error

2016-09-19 23:09 UTC, generalhenry requested changes
Pong working locally
Tests running into build issue.

2016-09-19 23:18 UTC, freignat91 reviewed
I got same issues than Henry's

2016-09-20 01:14 UTC, subfuzion commented
Fixed the last two tests.

2016-09-20 01:23 UTC, freignat91 approved these changes
tested ok

2016-09-20 01:46 UTC, merged