add registry ls and auto tag
appcelerator-archive/amp pull request #292
Opened 2016-10-06 12:50 UTC by freignat91

add:
- amp registry push [image] --domain [domain]
- amp registry ls

by default the domain is `local.amplifier.io`
the domain allow to tag automatically the image with the right domain name.
For instance:

amp registry push appcelerator/pinger:latest
will push the image registry.local.appelerator.io/pinger:latest in the amp registry
(with auto tag from appcelerator/... to registry.local.appcelerator.io/...)

test:
- build amp: rm -rf vendor && glide install && make install
- start amp: sudo ./swarm start
- push image: amp registry push appcelerator/pinger:latest
- verify ok: amp registry ls
- display: {"repositories":["pinger"]}

2016-10-06 13:38 UTC, ndegory commented
@freignat91 you're referring to local.amplifier.io and local.appcelerator.io, is it a typo?

2016-10-06 13:53 UTC, ndegory commented
ok, checked in the sources, it's local.appcelerator.io

2016-10-06 14:01 UTC, ndegory requested changes
LGTM, tests passed.
Please check the comments inline before merging

2016-10-06 14:01 UTC, ndegory commented on cmd/amp/registry.go
> +			return fmt.Errorf("Invalide image name %s", image)
s/Invalide/Invalid/

2016-10-06 14:01 UTC, ndegory commented on cmd/amp/registry.go
>  // RegistryPush displays resource usage statistcs
s/statistcs/statistics

2016-10-06 14:01 UTC, ndegory commented on cmd/amp/registry.go
> +// RegistryPush displays resource usage statistcs: localhost:5000/v2/_catalog
s/statistcs/statistics/

2016-10-06 14:10 UTC, freignat91 commented on cmd/amp/registry.go
> +// RegistryPush displays resource usage statistcs: localhost:5000/v2/_catalog
done

2016-10-06 14:16 UTC, ndegory approved these changes

2016-10-06 14:17 UTC, merged

2016-10-10 00:52 UTC, subfuzion commented
@freignat91  @ndegory  What issue is this associated with?