Stack network stage 2
appcelerator-archive/amp pull request #304
Opened 2016-10-12 13:36 UTC by freignat91

Be able to create custom networks and associate stack services to them in order to establish private communication between services from separate stacks.

test:
- stop amp:  sudo ./swarm stop
- pull images: ./swarm pull
- build amp: glide cc && rm -rf vendor && glide install && male install
- start amp: sudo ./swarm start
- create stack test1: amp stack up test1 -f api/rpc/stack/test_samples/sample-10-1.yml
- create stack test2: amp stack up test2 -f api/rpc/stack/test_samples/sample-10-2.yml
- verify:
    - stack test1 and test2 are up and running using: ./swarm monitor
    - custom network "amp_net" is created, using: docker network ls
    - container test1.pinger is able to ping test2.pinger
         - docker ps | grep test1.pinger  -> get the container id [containerId1]
         - docker exec -it [containerId1] sh
         - inside the container:  ping test2-pinger  -> should return a valid address
    - container test2.pinger is able to ping test1.pinger
         - docker ps | grep test2.pinger  -> get the container id [containerId2]
         - docker exec -it [containerId2] sh
         - inside the container:  ping test1-pinger  -> should return a valid address

Regression tests:
- make test

2016-10-13 08:52 UTC, ndegory requested changes
small fixes, mostly in comments

2016-10-13 08:52 UTC, ndegory commented on api/rpc/service/service.go
> +				//create names volume
s/names/named

2016-10-13 08:52 UTC, ndegory commented on api/rpc/service/service.go
> +				fmt.Println("create named volume"+list[0])
s/volume"/volume "/

2016-10-13 08:52 UTC, ndegory commented on api/rpc/service/service.go
> +			fmt.Println("create anonymous volume")
you mean "implicit bind type volume?"

2016-10-13 16:03 UTC, freignat91 commented on api/rpc/service/service.go
> +			fmt.Println("create anonymous volume")
A volume create by the container with no name and not bind to a host directory

2016-10-13 16:08 UTC, freignat91 commented on api/rpc/service/service.go
> +				fmt.Println("create named volume"+list[0])
done

2016-10-13 16:08 UTC, freignat91 commented on api/rpc/service/service.go
> +				//create names volume
done

2016-10-14 00:11 UTC, generalhenry approved these changes
Tested locally

2016-10-14 07:58 UTC, ndegory commented on api/rpc/service/service.go
> +			fmt.Println("create anonymous volume")
from what I see it's still bind to a host directory, it's just implicit (source is same as the target)

2016-10-14 07:58 UTC, ndegory approved these changes

2016-10-15 13:31 UTC, freignat91 commented on api/rpc/service/service.go
> +			fmt.Println("create anonymous volume")
yes, no explicite bind.

2016-10-17 21:17 UTC, subfuzion commented
Works great! LGTM 👍

2016-10-17 21:17 UTC, merged