Separating integration tests from unit tests
appcelerator-archive/amp pull request #449
Opened 2016-11-10 15:38 UTC by bquenin

Fixes #434 

## Verification
    $ ./swarm pull
    $ ./swarm start
    $ make install
    $ make test

2016-11-10 23:16 UTC, generalhenry requested changes
Error on MacOS

```
bash-3.2$ make install
find: -printf: unknown primary or operator
find: -printf: unknown primary or operator
```

2016-11-10 23:56 UTC, generalhenry commented
looks like
``` make
UNIT_TEST_PACKAGES        := $(shell gfind .       -type f -name '*_test.go' -not -path './tests/*' $(EXCLUDE_DIRS_FILTER) | xargs -n1 dirname | sort -u)
INTEGRATION_TEST_PACKAGES := $(shell gfind ./tests -type f -name '*_test.go'                        $(EXCLUDE_DIRS_FILTER) | xargs -n1 dirname | sort -u)
```
works

2016-11-14 13:23 UTC, bquenin commented
Thanks for your feedback @generalhenry, I fixed the PR accordingly

2016-11-14 16:43 UTC, generalhenry approved these changes

2016-11-14 16:53 UTC, merged