Cmd start
appcelerator-archive/amp pull request #455
Opened 2016-11-14 12:10 UTC by freignat91

related to  #437 

add amp commands: ([-v]: verbose, [-s]:silence, [f]: force
- amp pull |-v] [-s]
- amp start [-v] [-s] [-f]
- amp stop [-v] [-s] 
- amp status [-v]  [-s]
- amp monitor 

tests:
- stop amp using old script: `./swarm stop`
- remove all images and containers
- execute: `amp pull -v` :  pull all images needed for amp (-v: to have details)
- execute: `amp monitor` in another console to monitor amp
- execute: `amp start -v` in the first console
-execute: `amp status` it returns 'running'
- execute: `make test`
- execute: `amp stop`

2016-11-14 13:11 UTC, ndegory requested changes

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_infrastructure.go
> +		}, "nats", "influxdb")
nats is not an upstream dependency of telegraf-agent

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/plateform_status.go
> +package main
please rename the file to platform_status.go

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +	defaultHeaders := map[string]string{"User-Agent": "amplifier-1.0"}
can't we use the version from the binary instead? (at build time there's a VERSION env variable available)

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +	for {
there's a risk of infinite loop, should't we limit the retries and fail if it wasn't able to start all the services?

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +	//Verify fist that it exists at least one container running
s/it exists/there's/

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +	//no container running, then verify that it exists a container failling
s/it exists a container failling/there's at least a failed container/

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +	//No container running and failling then service is still starting without error
s/failling/failing/

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +	s.printf(colWarn, "Force mode: service %s is concidered as ready\n", service.name)
s/concidered/considered/
and I think it would be better to say "status of service %s is forced to 'ready'\n"

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +			return fmt.Errorf("Impossible to get volume list: %v\n", err)
s/Impossible/Failed/

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_manager.go
> +		data := make([]byte, 1000, 1000)
what happens if the stack is big enough to fill the array?

2016-11-14 13:11 UTC, ndegory commented on cmd/amp/platform_pull.go
> +func pullAMPImages(cmd *cobra.Command, args []string) error {
amp pull --server=remote-server:8080 pulls images locally, which doesn't make any sense

2016-11-14 13:31 UTC, ndegory requested changes

2016-11-14 13:31 UTC, ndegory commented on .travis.yml
> +  - appp start
is it amp?

2016-11-14 13:31 UTC, ndegory commented on cmd/amp/platform_manager.go
> +		fmt.Printf("%s%s%s%s%s%s\n", col("ID", cols[0]), col("SERVICE", cols[1]), col("STATUS", cols[2]), col("MODE", cols[3]), col("REPLICAS", cols[4]), col("TASK FAILED", cols[5]))
s/TASK FAILED/FAILED TASKS/

2016-11-14 13:33 UTC, freignat91 commented on cmd/amp/platform_infrastructure.go
> +		}, "nats", "influxdb")
ok

2016-11-14 13:34 UTC, freignat91 commented on cmd/amp/plateform_status.go
> +package main
ok

2016-11-14 13:35 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +	defaultHeaders := map[string]string{"User-Agent": "amplifier-1.0"}
In fact, it should have version here

2016-11-14 13:36 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +	for {
ok

2016-11-14 13:39 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +		data := make([]byte, 1000, 1000)
it's not possible, it's not related to stack but to the reader which adjust data to the array size

2016-11-14 13:40 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +	//Verify fist that it exists at least one container running
ok

2016-11-14 13:41 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +	//no container running, then verify that it exists a container failling
ok

2016-11-14 13:41 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +	//No container running and failling then service is still starting without error
ok

2016-11-14 13:42 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +			return fmt.Errorf("Impossible to get volume list: %v\n", err)
ok

2016-11-14 13:42 UTC, freignat91 commented on cmd/amp/platform_pull.go
> +func pullAMPImages(cmd *cobra.Command, args []string) error {
to be improved later

2016-11-14 13:43 UTC, freignat91 commented on cmd/amp/platform_manager.go
> +	s.printf(colWarn, "Force mode: service %s is concidered as ready\n", service.name)
ok

2016-11-14 13:44 UTC, freignat91 commented on .travis.yml
> +  - appp start
fixed

2016-11-14 14:01 UTC, ndegory commented on cmd/amp/platform_manager.go
> +		data := make([]byte, 1000, 1000)
ok

2016-11-14 14:06 UTC, ndegory commented on cmd/amp/platform_pull.go
> +func pullAMPImages(cmd *cobra.Command, args []string) error {
I disagree, the --server (or the .amp.yaml config) is a configuration for all command of this binary. It should apply to the pull command. If I configure the CLI to manage an infra stack on a remote swarm manager, I don't want it to pull images locally.

2016-11-14 14:07 UTC, ndegory commented on .travis.yml
> +  - app start
what is app? Shouldn't it be amp?

2016-11-14 14:48 UTC, freignat91 commented on cmd/amp/platform_pull.go
> +func pullAMPImages(cmd *cobra.Command, args []string) error {
yes, i got that, but it's not the target of the PR for now.

2016-11-15 15:38 UTC, ndegory approved these changes

2016-11-16 18:37 UTC, merged