Amp cluster management
appcelerator-archive/amp pull request #519
Opened 2016-12-02 15:49 UTC by freignat91

Related to #512 

For the ones granted, here is a video to explain more in details the PR features
https://drive.google.com/a/axway.com/file/d/0B3HdJx5HHXGcUzR1ZVRSMGVURVk/view?usp=sharing

see also the discussion on the topic "Short demo on amp cluster features" on Mobilize

to test locally:
make install
./shrink.sh local
amp-cluster pf start --local -v

amp-cluster pf monitor (on another console)
amp-cluster node ls
amp-cluster node count
amp-cluster pf stop

to test on Amazon amp cluster after having used the Nicolas's amp-bootstrap installation:
-so prerequisite is to have a running swarm cluster, on the manager exeucute:
amp-cluster cluster start --tag cluster
Tha's all on manager.
on amp cli supported client machine execute:
-amp-cluster --server [managerAddress]:31315 node ls  (to see the nodes status)
-amp-cluster --server [managerAddress]:31315 node purge --container --image (if needed)
-amp-cluster --server [managerAddress]:31315 pf pull -v (all amp images are pulled on all nodes)
-amp-cluster --server [managerAddress]:31315 pf start -v
-amp-cluster --server [managerAddress]:31315 pf monitor (on another console)

-amp-cluster --server [managerAddress]:31315 pf pull -v

2016-12-02 22:59 UTC, generalhenry requested changes
Docker: 1.13.0-rc2 

freshly restored to factory defaults

`docker swarm init`
`make install`
`./shrink.sh local`
`amp-cluster pf start --local -v`

Result:

Service cluster-agent starting
Service cluster-server starting
Cluster services started
Connection to cluster server error: grpc: timed out when dialing

Reason:

my ~/.amp.yaml contains a normal serverAddress entry

The server address configuration needs to be independently set

2016-12-02 23:11 UTC, generalhenry commented on cmd/amp-cluster/cli.go
> +		g.printfc(colError, "Arg error: %v\n", err)
The pattern of `g.printfc(colError, errorDescription, err); os.exit(1)` is common enough make a `g.fatalc(errorDescription, err)` method

2016-12-02 23:18 UTC, generalhenry commented on cmd/amp-cluster/cli_node_count.go
> +		fmt.Println("\033[2J\033[0;0H")
These printlns are both arcane and used a number of places maybe a `g.followStart(follow bool)` and `g.followLn(follow bool)`

2016-12-02 23:25 UTC, generalhenry commented on cmd/cluster-server/servergrpc/cluster-server.proto
> +        rpc GetClientStream (stream ClientMes) returns (stream ClientMes) {}
grpc-gw annotations would be nice

2016-12-05 07:04 UTC, freignat91 commented
About server address configuration, as explained in the discussion topic "Short demo on amp cluster features" on Mobilize, i was waiting the decisions to merge or not the cluster-cli into amp-cli or cluster-server into amplifier to finalize the configuration, but in the meantime i can make it separated yes.

2016-12-05 07:08 UTC, freignat91 commented on cmd/amp-cluster/cli.go
> +		g.printfc(colError, "Arg error: %v\n", err)
yes, why not. I prefer explicit Exit command, then hidden one, but to be aligned with Go style, it's ok.

2016-12-05 08:13 UTC, freignat91 commented on cmd/amp-cluster/cli_node_count.go
> +		fmt.Println("\033[2J\033[0;0H")
done

2016-12-05 09:54 UTC, freignat91 commented on cmd/amp-cluster/cli.go
> +		g.printfc(colError, "Arg error: %v\n", err)
done

2016-12-05 10:06 UTC, freignat91 commented on cmd/cluster-server/servergrpc/cluster-server.proto
> +        rpc GetClientStream (stream ClientMes) returns (stream ClientMes) {}
yes sure, but first get agreement on the cli verbs/structure and inclusion or not in amp cli.

2016-12-06 19:01 UTC, generalhenry approved these changes

2016-12-19 16:04 UTC, subfuzion commented
@freignat91 @ndegory It's taken a while for me to review, but excellent work. Thank you for this contribution. 👍 

I'm merging this into v0.5.0-rc1 for now for additional evaluation.

2016-12-19 16:04 UTC, merged