AMP Bootstrap
appcelerator-archive/amp pull request #528
Opened 2016-12-07 15:43 UTC by ndegory

resolves #306 

subcommand of amp cluster cli to bootstrap a node (Docker, Swarm, cluster agent and server services)

```
$ amp-cluster bootstrap -h
Installs Docker, setups Swarm, run the AMP agent

Usage:
  amp-cluster bootstrap [flags]

Aliases:
  bootstrap, bs

Flags:
  -c, --create         initializes the Swarm (needs option -m)
      --host string    Swarm manager hostname
  -m, --manager        bootstraps a Swarm manager node
      --port string    Swarm manager port (default "2377")
      --tag string     AMP image version (default "v0.4.0-dev")
      --token string   Swarm join token

Global Flags:
      --config string   Config file (default is $HOME/.amp.yaml)
      --debug           display debug information
      --server string   define the remote server address (default "127.0.0.1:31315")
      --silence         No output
  -v, --verbose         Verbose output
```

2016-12-07 17:35 UTC, generalhenry approved these changes

2016-12-07 18:20 UTC, ndegory commented
tested: manager initialization (sudo amp-cluster bootstrap -m -c --tag cluster) on Ubuntu 16.04 and CentOS 7.

2016-12-08 08:30 UTC, freignat91 requested changes

2016-12-08 08:30 UTC, freignat91 commented on cmd/amp-cluster/bootstrap.go
> +var Manager bool
These vars should have their first letter lowercase concidering they are only local

2016-12-08 08:30 UTC, freignat91 commented on cmd/amp-cluster/bootstrap.go
> +		log.Fatalf("Failed to enable the Docker service: %s\n", err)
use g.fatalc("%v\n", err) in place of log.Fatalln to have color output
globally use g.printfc(...) in place of log to have color output the same way then in the orther commands
including in bootstrap-docker.go file

2016-12-08 08:30 UTC, freignat91 commented on cmd/amp-cluster/bootstrap-docker.go
> +	cmd.Stderr = &stderr
if you want to see output you can also use:
    cmd.Stdout = os.Stdout
    cmd.Stderr = os.Stderr

2016-12-08 08:30 UTC, freignat91 commented on cmd/amp-cluster/bootstrap-docker.go
> +	_, err := c.dockerClient.ImagePull(c.ctx, image, types.ImagePullOptions{})
you don't use the reader, so you don't know if pull has error or not during pull

2016-12-08 14:42 UTC, ndegory commented on cmd/amp-cluster/bootstrap.go
> +var Manager bool
ok, done

2016-12-08 14:42 UTC, ndegory commented on cmd/amp-cluster/bootstrap.go
> +		log.Fatalf("Failed to enable the Docker service: %s\n", err)
ok, done (but now I have to background color issue...)

2016-12-08 14:45 UTC, ndegory commented on cmd/amp-cluster/bootstrap-docker.go
> +	cmd.Stderr = &stderr
I can't, I don't want to output it on the console, I use the output later

2016-12-08 14:45 UTC, ndegory commented on cmd/amp-cluster/bootstrap-docker.go
> +	_, err := c.dockerClient.ImagePull(c.ctx, image, types.ImagePullOptions{})
ok, done

2016-12-08 15:01 UTC, freignat91 approved these changes
LGTM

2016-12-08 15:03 UTC, merged