Improved Regex
appcelerator-archive/amp pull request #544
Opened 2016-12-13 02:20 UTC by neha-viswanathan

Updated regex-lookup.yml by removing redundant characters in the regular expressions.

2016-12-13 18:56 UTC, generalhenry approved these changes

2016-12-15 15:01 UTC, subfuzion requested changes

2016-12-15 15:01 UTC, subfuzion commented on tests/cli/lookup/regex-lookup.yml
> +docker-service-list: ID\s+NAME\s+REPLICAS\s+IMAGE\s+COMMAND\s*([a-zA-Z0-9\s\.\-:/]*){1,}
Can you verify this is correct ("COMMAND")?

2016-12-15 15:02 UTC, subfuzion commented
Please resolve conflicts and double-check the regex for docker-service-list so I can merge. Thanks.

2016-12-15 20:58 UTC, neha-viswanathan commented
`docker-service-list` is not being used. So I've removed it.

2016-12-16 17:53 UTC, subfuzion approved these changes

2016-12-16 17:53 UTC, subfuzion commented
LGTM

2016-12-16 17:53 UTC, merged