issue 573-576
appcelerator-archive/amp pull request #583
Opened 2016-12-14 09:12 UTC by freignat91

add grpc errors for stack and stats

test:
-make install
-../shrink.sh local
- amp pf start -v --local
- make test

2016-12-14 16:40 UTC, generalhenry commented on api/rpc/stack/parse.go
> +		return nil, grpc.Errorf(codes.InvalidArgument, "%v", err)
The parsing is being done client side currently, not that these hurt there.

2016-12-15 15:55 UTC, subfuzion requested changes
@freignat91 Looks good. Please resolve conflicts so I can merge. Thanks.

2016-12-16 12:28 UTC, freignat91 commented on api/rpc/stack/parse.go
> +		return nil, grpc.Errorf(codes.InvalidArgument, "%v", err)
oh yes, excellent, i didn't see that it has been moved client side. Good! 
I updated back the pr for parse.go

2016-12-16 17:55 UTC, subfuzion approved these changes

2016-12-16 17:55 UTC, merged