amp version functions correctly
appcelerator-archive/amp pull request #589
Opened 2016-12-14 19:14 UTC by neha-viswanathan

Fix for issues #547 #561 #565 

* Fixed `amp version`, `amp --version`, `amp -V` to only display amp version
* Formatted help descriptions
* Formatted amplifier flags to lowercase

To test #547 
```
$ make install
$ amp version
amp (cli version: v0.4.0-dev, build: bdc1a369)
$ amp --version
amp (cli version: v0.4.0-dev, build: bdc1a369)
$ amp -V
amp (cli version: v0.4.0-dev, build: bdc1a369)
```

2016-12-15 00:52 UTC, JosephGJ approved these changes
LGTM

2016-12-15 09:41 UTC, ndegory requested changes
LGTM, with requested changes. Also, we should probably add a Long Cobra description to the RootCmd, but that means changing the usage template in main.go.

2016-12-15 09:41 UTC, ndegory commented on cmd/amp/platform_manager.go
> +		return fmt.Errorf("Impossible to connect to Docker on: %s\n%v", DockerURL, err)
Error message [should not be capitalized](https://github.com/golang/go/wiki/CodeReviewComments#error-strings). A PR is waiting to be merged with same kind of warnings: #545

2016-12-15 09:41 UTC, ndegory commented on cmd/amp/registry.go
> +		return errors.New("Refusing to create a tag with a digest reference")
should not be capitalized

2016-12-15 09:41 UTC, ndegory commented on cmd/amp/topic-create.go
> +		return errors.New("Must specify topic name")
should not be capitalized

2016-12-15 09:41 UTC, ndegory commented on cmd/amp/topic-create.go
> +		return errors.New("Must specify topic name")
ditto

2016-12-15 16:02 UTC, subfuzion requested changes
@neha-viswanathan I agree with @ndegory. Looks good overall. Please make the requested changes and also resolve merge conflicts. Thanks.

2016-12-15 18:23 UTC, neha-viswanathan commented
@ndegory I will add the Cobra Description to the root command as a different PR.

2016-12-16 00:12 UTC, ndegory approved these changes

2016-12-16 19:09 UTC, subfuzion approved these changes

2016-12-16 19:09 UTC, merged

2016-12-19 10:15 UTC, ndegory commented
@neha-viswanathan there's an issue with this PR (already merged), previous commits (at least a part of #592) have been reverted. I noticed it with the output of ```amp config```.
I think you should revert it, restore the branch, and rebase it from master.