updated changelog for 0.4.0 (partial)
appcelerator-archive/amp pull request #602
Opened 2016-12-19 16:58 UTC by ndegory

Changelog update (ndegory PRs)

2016-12-19 20:50 UTC, bquenin commented on CHANGELOG.md
> +### Vendoringttps://github.com/appcelerator/amp/pull/586
Probably a typo here

2016-12-19 21:14 UTC, bquenin requested changes
Also, it seems that 0.3.0 CHANGELOG has disappeared

2016-12-19 22:34 UTC, JosephGJ commented on CHANGELOG.md
> +### Vendoringttps://github.com/appcelerator/amp/pull/586
Removed.

2016-12-19 23:03 UTC, bquenin approved these changes

2016-12-19 23:04 UTC, bquenin submitted a review, later dismissed
Also, it seems that 0.3.0 CHANGELOG has disappeared

2016-12-20 17:17 UTC, subfuzion commented
LGTM. Thanks @ndegory 👍

2016-12-20 17:18 UTC, merged