Adding ladon to vendor
appcelerator-archive/amp pull request #696
Opened 2017-01-13 10:29 UTC by bquenin

This PR is just a sandbox to illustrate the usage of ladon and to check wether or not we xant to use it for access control.

The first commit ladon vendoring.

2017-01-31 21:47 UTC, ndegory requested changes
vendors have been updated on master since you submitted this PR, you will have to rebase

2017-01-31 21:47 UTC, ndegory commented on glide.yaml
> +  version: 976c720a22c8eb4eb6a0b4348ad85ad12491a506
I've failed to find this commit of testify on the repo, is there any issues with tag 1.1.4?

2017-02-01 15:25 UTC, bquenin commented on glide.yaml
> +  version: 976c720a22c8eb4eb6a0b4348ad85ad12491a506
This PR is not for master, but for branch v0.6.x. I had an issue with testify at the time, I'll have a look at it again.

2017-02-03 17:54 UTC, bquenin commented
Closing this PR until we have a first implementation of the permission model.

2017-02-03 17:54 UTC, closed without merging