Updated command usage
appcelerator-archive/amp pull request #701
Opened 2017-01-19 00:33 UTC by neha-viswanathan

Ref: #692 

Modified the usage for the CLI commands. Added `[]` wherever necessary.

2017-01-19 17:29 UTC, generalhenry commented on cmd/amp/config.go
> +		Use:   "config [ARG..]",
`[KEY] [VALUE]`

2017-01-19 21:49 UTC, neha-viswanathan commented on cmd/amp/config.go
> +		Use:   "config [ARG..]",
Updated

2017-01-23 18:51 UTC, JosephGJ requested changes
Minor change. LGTM

2017-01-23 18:51 UTC, JosephGJ commented on cmd/amp/function.go
>  	If successful, a function id is returned.`,
Nit Picky. This line creates an indent on the CLI.

```
The create command registers a function with the specified name and image.
        If successful, a function id is returned.
```

2017-01-23 19:34 UTC, JosephGJ approved these changes

2017-01-25 20:25 UTC, subfuzion approved these changes
LGTM

2017-01-25 20:25 UTC, merged