WIP: Cluster deployment on AWS
appcelerator-archive/amp pull request #909
Opened 2017-04-07 09:40 UTC by ndegory

Please don't merge yet.

This PR adds the missing elements for AMP stack deployment on AWS.

- symlink for hack/deploy: hack/deploy-aws
- run terraform apply --var "cidr_remote_api=$(curl -sf ifconfig.co)/32" ./bootstrap/terraform-aws
- the cluster id and the manager leader ip are printed
- add the leader IP as an insecure registry on your host, restart the engine
- ./hack/deploy-aws $clusterid

PS: if you don't have the terraform binary, you can use the Docker image

2017-04-08 23:36 UTC, subfuzion reviewed
Ok, happy to see aws deployment unified to a single starting point, but to be honest, I feel that my deploy script was already too complicated and wasn't happy with it. Now that complexity has increased. I don't like that we have multiple functions performing conditional case checks for `localhost` or `aws`. What happens when we support more provider backends? Really, the script should determine the deployment target then run `cluster.localhost.sh` or `cluster.aws.sh` specialized scripts for specialized cluster management implementation, and then this script should continue and run the generic smoke tests. I can live with it between now and our milestone deadline as long as we commit to a less brittle strategy afterwards, but we want to look for opportunities to reduce complexity, not increase it, as we proceed.

2017-04-08 23:36 UTC, subfuzion commented on hack/deploy
> +readonly stacks_to_deploy="amp1 amp2 amp3"
Do you need this (`stacks_to_deploy`)?

2017-04-08 23:36 UTC, subfuzion commented on hack/deploy
> +readonly rapi_cidr="$(curl -sf ifconfig.co)/32"
For what it's worth, you can make the curl call faster by just querying the ip: `ifconfig.co/ip`.

2017-04-08 23:36 UTC, subfuzion commented on hack/deploy
> +echo "$(deployment_target) deployment"
A bit concerned about blossoming complexity of this script, but at least as a style issue, let's avoid executable code between function declarations (ref: Google's bash style guide for [Function Location](https://google.github.io/styleguide/shell.xml?showone=Function_Location#Function_Location)).

2017-04-08 23:36 UTC, subfuzion commented on hack/deploy
> +    export DOCKERHOST
It's a bash script, so `export DOCKERHOST=$dockerhost` is fine.

2017-04-08 23:48 UTC, subfuzion commented
Local deploy failed:

```
$ hack/dev
. . .
final service replica smoke check failed (exit 1)
clean up
destroy amp-manager-f573e897-7aa0-4516-a195-42ee91039e97 initiated
destroy amp-worker-f573e897-7aa0-4516-a195-42ee91039e97 initiated
destroy amp-proxy-f573e897-7aa0-4516-a195-42ee91039e97 initiated
infrakit has been destroyed
registry has been destroyed
client certificates have been removed
configuration volume deleted
```

Ran `hack/dev` again:

```
$ hack/dev
local deployment
cluster is not healthy, please fix the issue and try again (exit 1)
clean up
client certificates have been removed
no configuration volume to delete
```

Expected second deployment to succeed.

2017-04-08 23:54 UTC, ndegory commented on hack/deploy
> +readonly stacks_to_deploy="amp1 amp2 amp3"
not anymore, I'll remove it

2017-04-09 00:14 UTC, subfuzion requested changes
Local deployments fail, despite running `./bootstrap/bootstrap -d` or manually removing all containers and volumes, etc.

The issue is that `hack/dev` now fails, probably because it's supplying a fixed cluster id. I can run `hack/deploy` directly.

2017-04-09 05:31 UTC, ndegory commented
@subfuzion comments have been taken into account and local deployment with the hack/dev script is now working.

2017-04-12 18:22 UTC, subfuzion commented on hack/swarmcheck
> +    if [[ $? -ne 0 ]]; then nc=0; fi
Please leave the commented out version of the previous filter test for `accepted` and a TODO comment to investigate whether this is a docker bug.

2017-04-12 18:44 UTC, subfuzion approved these changes
Other than the reservations I've already expressed about increasing script complexity, this looks good for now. Thanks @ndegory

2017-04-12 18:44 UTC, merged