[Monitoring] add global_total dashboard
appcelerator-archive/amp pull request #939
Opened 2017-04-10 22:22 UTC by freignat91

add global_total dashboard in kibana dashboard to have to real total and not only the average value in global dashboard.

To be integrated in kibana.

To testit

- hack/deploy
- launch kibana on localhost:50106
- go to "Mnagement" menu
- go to "Saved Object" tab
- clic on "import" button and choose the file: cmd/ampbeat/kibana-amp-dashboard.json
- clic on "Dashboard", select "global_total"

2017-04-11 03:34 UTC, ndegory approved these changes
LGTM

2017-04-11 17:08 UTC, ndegory requested changes

2017-04-11 17:08 UTC, ndegory commented on images/kibana/README.md
> +- 5.3.0-2, 5.3, latest
5.3.0-2 is already planned in PR #909 
please rebase once it's merged and update to 5.3.0-3.

2017-04-12 00:24 UTC, freignat91 commented on images/kibana/README.md
> +- 5.3.0-2, 5.3, latest
yes, once the #909 is merged

2017-04-12 16:21 UTC, ndegory approved these changes

2017-04-12 19:04 UTC, subfuzion approved these changes

2017-04-12 19:04 UTC, merged